name: cicd
on:
  push:
  pull_request:
  release:
    types: published
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.1.3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and run tests
      run: |
        python -V
        make setup
  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Python
      uses: actions/setup-python@v2.1.3
      with:
        python-version: '3.8'
    - name: Install dependencies and build
      run: |
        echo "$GITHUB_REF"
        python -V
        pip install -U pip setuptools wheel twine
        python ./setup.py sdist bdist_wheel
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload ./dist/*
